name: Expo CI

on:
  workflow_dispatch:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  lint_and_test:
    name: Lint and Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ROTA-TCC'

      - name: Configurar .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          echo "@ROTA-TCC:registry=https://npm.pkg.github.com/" >> .npmrc

      - name: Instalar dependências
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm install

      - name: Rodar o Lint
        run: pnpm run lint

      - name: Rodar Testes
        run: pnpm run test

